### ISSUE TITLE
Unnecessary delay between tests

### ISSUE THREAD

**Issue by namp007** [driversti/erepsistant#1]
I've seen your problems with the https://github.com/tomakehurst/wiremock/issues/97 issue.
Perhaps https://github.com/tomakehurst/wiremock/issues/97#issuecomment-615198151 would resolve this issue and prevent the unnecessary delay between the tests?
You'd have to manually configure the wiremockserver though.
(I would have created a PR, but I don't have JAVA 13 on my device and also presumed that you would like to implement your own way.)

**Comment by driversti** [comment]
Unfortunately, in my case, this trick doesn't work. I've got:

                                            Request was not matched
                                            =======================

    ------------------------------------------------------------------------------------------------ 
    | Closest stub                                     | Request
    ------------------------------------------------------------------------------------------------ 
                                                       |
    POST                                               | POST
    /economy/marketplaceAjax                           | /economy/marketplaceAjax
                                                       |
    Content-Type: application/x-www-form-urlencoded    | Content-Type: application/x-www-form-urlencoded
    Connection: close                                  | Connection: keep-alive  <<<<< Header does not match
                                                       |
                                                       |
    ------------------------------------------------------------------------------------------------

A short example of a stub:
    
    ...
    "headers": {
      "Content-Type": {
        "equalTo": "application/x-www-form-urlencoded"
      },
      "Connection": {
        "equalTo": "close"
      }
    },
    ...

**Comment by namp007** [comment]
Did you perhaps accidentally change the request part instead of the response part? (because the request part should stay unchanged) resulting in the matcher not working.

**Comment by driversti** [comment]
Yes, this is exactly what I did.
Nevertheless, I've used your suggestion and this did a trick! Thanks a lot, mate :)
